---
title: "kickstarter_notebook"
output: html_notebook
---

```{r}
package_install = c("shiny", "leaflet","lubridate","tidyverse","countrycode",'treemap',"devtools","geojsonio","ggthemes")
install.packages(package_install)
library("tidyverse")
library("lubridate")
#library("tidyr")
#library("dplyr")
library("shiny")
library("leaflet")
library("countrycode")
library("treemap")
library("ggthemes")
library("devtools")
library("geojsonio")
library("rgdal")
install_github("timelyportfolio/d3treeR")
library("d3treeR")
 
```

Please wait a few minutes, downloading can be a bit long
```{r}
ksprojects <- read.csv(url("https://perso.esiee.fr/~hamamic/cgi-bin/R/kickstarter/ks-projects-201801.csv"),encoding="UTF-8")
```

New dataframe to keep the original unmodified
```{r}
ksprojects1 <- ksprojects
```

date conversion
```{r}
ksprojects1 %>% mutate(launched = as.POSIXct(launched,format="%Y-%m-%d %H:%M:%S")) %>%
                mutate(deadline = as.POSIXct(deadline,format="%Y-%m-%d")) -> ksprojects1
```


removing unacessary things
```{r}
ksprojects1$usd.pledged <- NULL #wrong conversion
ksprojects1 %>% filter(!(launched <= as.POSIXct('2009-01-01 00:00:00'))) %>%  #dates error
                filter(!(launched >= as.POSIXct('2018-01-01 00:00:00'))) %>%  #year not finished
                filter(!(state == 'live')) %>%                                #out of date data
                filter(!(state == 'undefined')) %>%                           #project data errors
                filter(!(country == "N,0\"")) -> ksprojects1                  #coordinates error & backers error


# "N,0\"" country is null island; name to which coordinates erroneously set to 0,0
#delete levels ? use unique()
```

adding new variables that should be interesting to analyse
```{r}
                #year when the project launched
ksprojects1 %>% mutate(year = year(ksprojects1$launched))  %>%
                #conversion of the project name to character
                mutate(name = as.character(name)) %>%               
                #funding percentage     
                mutate(funding_percentage = (usd_pledged_real/ksprojects1$usd_goal_real)*100) %>% 
                #average per backers
                mutate(avrg_per_bckers = ksprojects1$usd_pledged_real/backers) %>%                
                #difference between launch date and deadline in days
                mutate(days_to_complete = as.numeric(round(difftime(ksprojects1$deadline,ksprojects1$launched,units="days")))) -> ksprojects1

```

Dealing with NA and Inf
```{r}
ksprojects1 %>% mutate(avrg_per_bckers = replace(avrg_per_bckers, is.infinite(avrg_per_bckers), NA)) %>% 
                mutate(avrg_per_bckers = replace(avrg_per_bckers, is.na(avrg_per_bckers), 0)) -> ksprojects1
```

```{r}
cntrycode <- as.character(unique(ksprojects1$country))
#Conversion of country code to character
cntryname <- countrycode(unique(ksprojects1$country), "iso2c", "country.name.fr") 
#Conversion of country code to french country name 
cntryname[19] <- "Hong Kong"
#error with Hong Kong
names(cntrycode) <- cntryname
rm(cntryname)
```


```{r}
#worldcntry <- geojsonio::geojson_read("custom.geo.json", what = "sp") #Load geojson map
worldcntry <- geojsonio::geojson_read("https://perso.esiee.fr/~hamamic/cgi-bin/R/kickstarter/custom.geo.json", what = "sp")

```


```{r}
ksprojects1 %>% rename(project = name) %>% group_by(country) %>% filter(usd_pledged_real == max(usd_pledged_real)) %>% select(project,country,usd_pledged_real) -> mx_name_cntry #project with max pledged per country 
ksprojects1 %>% count(country) -> n_cntry #number of projects per country
worldcntry %>% merge(n_cntry, by.x="iso_a2", by.y="country", all = TRUE) %>%
merge(mx_name_cntry, by.x="iso_a2", by.y="country", all = TRUE) -> worldcntry #add data to geojson
rm(mx_name_cntry,n_cntry)

#table(ksprojects1$country)
```

```{r}
#leaflet

pal <- colorBin("YlOrRd", domain = worldcntry$n, bins = c(0, 50, 100, 200, 500, 1000, 2000, 4000,5000,Inf)) #color palet
labels <- sprintf(
  "
  Pays : %s <br>
  Nombre de projets total : <strong>%s</strong> <br/> 
  Projet ayant récolté le plus : <br> 
  %s <br> 
  <strong>%s$</strong>
  ",
  worldcntry$name_long, worldcntry$n, worldcntry$project, worldcntry$usd_pledged_real
) %>% lapply(htmltools::HTML)

```

